[package]
name = "harmonicity-plugin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs"] }
rand = "0.9.1"
rand_pcg = "0.9.0"

[workspace]
members = ["xtask"]
